### ISSUE TITLE
Consecutive alerts, the first is only visible.

### ISSUE THREAD

**Issue by victor-shelepen** [agneym/ir-toast#7]
The prompt logic is implemented basing on the library. So Prompt is called and then a toast. The next toasts are not shown. I've checked with consecutive toasts only, the same issue. I chained well, checked twice :)

**Comment by agneym** [comment]
That is unfortunately the default behaviour for ionic toasts. For using multiple toasts, see the [official forums](https://forum.ionicframework.com/t/multiple-toasts/84048)
